### ISSUE TITLE
GoOracle Setting is not configurable On Mac Sublime3 

### ISSUE THREAD

**Issue by ypwu1** [waigani/GoOracle#16]
GoOracle Setting is not configurable On Mac Sublime3. config file can be open but just read only.

**Comment by kylebrandt** [comment]
Same problem

**Comment by nfiniteset** [comment]
I ran into the same problem. To get around it save this stuff:

    {
      // Example settings. Replace these with your own.
      // "env": {},
      // "oracle_scope": ["github.com/juju/juju/cmd/juju", "github.com/juju/juju/cmd/jujud"],
      // "oracle_format": "",
    }

into a new file here:

    ~/Library/Application Support/Sublime Text 3/Packages/GoOracle/User.sublime-settings

**Comment by tschundeee** [comment]
Same Problem here... Needs to be fixed I guess :+1:

**Comment by jasdel** [comment]
Same issue with Ubuntu 14.04 & SublimeText 3

```
~/.config/sublime-text-3/Packages/GoOracle/User.sublime-settings
```

**Comment by brakmic** [comment]
Windows 8.1 too

**Comment by brakmic** [comment]
Windows users should do this:

a) first, unpack the GoOracle.sublime-package in AppData\Roaming\Sublime...\Installed Packages directory
b) then modify the User.sublime.settings
c) Compress the modified settings file plus all other files into a new package called GoOracle.sublime-package but DO NOT create a new directory, just a new package. Also don't use any kind of compression: just save the "combined" files.

Now you can use GoOracle with your individual settings applied.

**Comment by hkic** [comment]
(Tested on ST3 and Mac Yosemite)

To run GoOracle properly and SAVE YOUR TIME!

1. Install must-have components
   `go get golang.org/x/tools/oracle`
   `go get golang.org/x/tools/cmd/oracle`

   > Otherwise, `oracle not found`.

2. Create and Save user setting files (refer to above @nfiniteset workaround)

   Mac: `~/Library/Application Support/Sublime Text 3/Packages/GoOracle/User.sublime-settings`

   Must-have settings: Change `PATH` accordingly.
   `oracle_scope` is path under `$GOPATH/src/`.

   * It can be specified for individual project: [@dr2chase solution](https://github.com/waigani/GoOracle/issues/13#issuecomment-98177541)

   * But you can also manually change the `oracle_scope` for each project
     ```
     {
         "env": { "GOPATH": "$HOME/Go", "GOROOT": "/usr/local/opt/go/libexec", "PATH": "$GOROOT/bin:$GOPATH/bin:$PATH" },
         "oracle_scope": ["projects/myproj"],
    }
    ```

   > Otherwise, get stuck in "Running oracle callees command..." and no output returned.
   "View">"Show Console" shows console error.
   `Traceback (most recent call last):
  File "goOracle in /Users/gopher/Library/Application Support/Sublime Text 3/Installed Packages/GoOracle.sublime-package", line 46, in on_done
  File "goOracle in /Users/gopher/Library/Application Support/Sublime Text 3/Installed Packages/GoOracle.sublime-package", line 115, in oracle
TypeError`
   [GoOracle issue: Oracle never returns](https://github.com/waigani/GoOracle/issues/13)

   > Otherwise, `cgo failed: exec: "go": executable file not found in $PATH`
   > Related: [Oracle invocation error](https://github.com/GoClipse/goclipse/issues/91)

**Comment by ikandaswamy** [comment]
Is there any update on this issue ? I recently tried to use Go oracle with Sublime text 3 on osx and i keep hitting the error oracle: no packages specified for pointer analysis scope.

I manually downloaded the go-oracle package into my Packages dir for Sublime text 3, edited the user settings. Still get the above error. 

Does anyone have a solution to this issue ?
