### ISSUE TITLE
Error using Oracle on windows

### ISSUE THREAD

**Issue by jwendel** [waigani/GoOracle#22]
With ST3 with GoOracle on windows, when I try to issue any command with Oracle, I get the following error:

> Running oracle callees command...
>
> 'export' is not recognized as an internal or external command,
> operable program or batch file.

It looks like the "export" command on line 107 of goOracle.py is not a valid windows command for updating the path.  I believe you need to use the 'set' command for Windows.

(unless I'm missing some configuration for ST3 that is causing Oracle to not work)

**Comment by jwendel** [comment]
Even fixing the above, I get the following error next:

> Traceback (most recent call last):
>   File "goOracle in C:\Users\kyrra\AppData\Roaming\Sublime Text 3\Installed Packages\GoOracle.sublime-package", line 46, in on_done
>   File "goOracle in C:\Users\kyrra\AppData\Roaming\Sublime Text 3\Installed Packages\GoOracle.sublime-package", line 108, in oracle
> TypeError: 'NoneType' object is not subscriptable

**Comment by jwendel** [comment]
I got this fully working for Windows (with breaking linux/osx).  I'll see if I can this working for both and submit a pull request.

In-case I don't the main change is in the 'def oracle' for setting up cmd:

    cmd = "set GOPATH=%(go_path)s&&set PATH=%(path)s&&oracle -pos=%(file_path)s:%(pos)s -format=%(output_format)s %(mode)s %(scope)s"  % {

how you set environment variables, separate commands in the same line, and separate PATH variables differ in Windows.  The env variable setup in User.sublime-settings for windows needs to differ a bit as well.  For example:

    "env": { "GOPATH": "D:\\go", "PATH": "%PATH%;%GOPATH%\\bin" },
